version: '3.2'
services:
  turn:
    image: ghcr.io/elixir-webrtc/ex_turn:${TAG:-latest}
    container_name: turn
    restart: on-failure
    network_mode: host
    env_file: .env

  prometheus:
    image: prom/prometheus:v2.46.0
    container_name: prometheus
    restart: on-failure
    network_mode: host
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --web.listen-address="127.0.0.1:9090"
      - --storage.tsdb.path=/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus
    depends_on:
      - turn

  grafana:
    image: grafana/grafana:10.0.3
    container_name: grafana
    restart: on-failure
    network_mode: host
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/:/etc/grafana/
    depends_on:
      - prometheus
    environment:
      GF_SECURITY_ADMIN_PASSWORD: "${GF_SECURITY_ADMIN_PASSWORD}"
      GF_SECURITY_ADMIN_USER: "${GF_SECURITY_ADMIN_USER}"

volumes:
  grafana_data: {}
  prometheus_data: {}
