global:
  scrape_interval: 2s

  external_labels:
    monitor: 'codelab-monitor'

scrape_configs:
  - job_name: 'rel'
    static_configs:
      - targets: ['127.0.0.1:9568']

  - job_name: 'node'
    static_configs:
      - targets: ['127.0.0.1:9100']
