{
 "title": "TURN Stats",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Bitrate",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "targets": [
    { "expr": "listener_in_bitrate", "legendFormat": "Listener IN ({{listener_id}})" },
    {
     "expr": "allocation_in_bitrate",
     "legendFormat": "Allocation IN {{allocation_id}}"
    },
    {
     "expr": "allocation_out_bitrate",
     "legendFormat": "Allocation OUT {{allocation_id}}"
    }
   ]
  },
  {
   "title": "Total Run Queue Lengths",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "vm_total_run_queue_lengths_total",
     "legendFormat": "Total"
    },
    { "expr": "vm_total_run_queue_lengths_cpu", "legendFormat": "CPU" },
    { "expr": "vm_total_run_queue_lengths_io", "legendFormat": "IO" }
   ]
  },
  {
   "title": "VM Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "vm_memory_total", "legendFormat": "Total" }
   ]
  }
 ]
}